//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcoleEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class eleve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eleve()
        {
            this.lecons = new HashSet<lecon>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<System.DateTime> dateInscription { get; set; }
        public string prenom { get; set; }
        public string adresse { get; set; }
        public Nullable<int> creditHoraire { get; set; }
    
        public virtual eleve eleve1 { get; set; }
        public virtual eleve eleve2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lecon> lecons { get; set; }
    }
}
